### ISSUE TITLE
Name change

### ISSUE THREAD

**Issue by alimanfoo** [malariagen/mgenv#141]
Everyone's favourite question, what should we call this thing? 😄 

Originally I called this environment "binder" because this made it convenient to then include this repo as a submodule on another repo, which would then play well with anyone wanting to use that other repo with the [mybinder](https://mybinder.org/) service.

However, we stopped using mybinder a while back, and so the "binder" name for this repo is really a historical oddity.

Can anyone think of a better name?

**Comment by alimanfoo** [comment]
I wondered about "mgenv", which is riffing a bit on "[stenv](https://stenv.readthedocs.io/en/latest/index.html)" (which incidentally is a very parallel project to this one, maintaining a conda environment for the space telescope institute).

**Comment by alimanfoo** [comment]
Of course there is always "malariagenv" :)

**Comment by alimanfoo** [comment]
cc @leehart

**Comment by leehart** [comment]
I often use the abbreviation "mgen", which I pronounce "em jen".

+1 for mgenv (MalariaGEN environment)

The only potential clashes I've found so far are:
- An obscure Go package (v0.0.6) https://pkg.go.dev/github.com/elastic/go-txfile/dev-tools/lib/mage/mgenv
- "MGEnv is a simulated micro-grid domain modeled out of real data from the PecanStreet Inc. database." https://arxiv.org/pdf/1906.06178

**Comment by leehart** [comment]
Shall we start afresh or literally rename via https://docs.github.com/en/repositories/creating-and-managing-repositories/renaming-a-repository ?

**Comment by alimanfoo** [comment]
Should be able to rename this repo?

**Comment by leehart** [comment]
OK, I'll just rename this repo as it is.

**Comment by leehart** [comment]
- https://github.com/search?q=repo%3Amalariagen%2Fmgenv+binder&type=code
